// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

type AddResourceOrgRequest struct {
	ResourceId  uint64 `json:"ResourceId" validate:"required"`
	OrgId       uint64 `json:"orgId" validate:"required"`
	Description string `json:"description,optional"`
}

type AddServerOrgRequest struct {
	ServerId    uint64 `json:"serverId" validate:"required"`
	OrgId       uint64 `json:"orgId" validate:"required"`
	Description string `json:"description,optional"`
}

type AddServerTagRequest struct {
	ServerId uint64 `json:"serverId"`
	TagID    int    `json:"tagId"`
}

type AddUserToOrgReq struct {
	OrgId  uint64 `json:"orgId" validate:"required"`
	UserId uint64 `json:"userId"`
	Role   string `json:"role" validate:"required,oneof=member guest manager admin"`
}

type AdjustUserBalanceRequest struct {
	UserId       uint64 `json:"userId"`
	Amount       int64  `json:"amount"`
	CurrencyCode string `json:"currencyCode"`
	Reason       string `json:"reason"`
}

type AdminUserDeleteRequest struct {
	UserId uint64 `json:"userId" validate:"required"`
	Email  string `json:"email,optional"`
}

type AdminUserListRequest struct {
	Username string `json:"username,optional"`
	Email    string `json:"email,optional"`
	Phone    string `json:"phone,optional"`
	PaginationRequest
}

type AdminUserListResponse struct {
	Response
	Data AdminUserListResponseData `json:"data,omitempty"`
}

type AdminUserListResponseData struct {
	Users []UserResponseData `json:"users"`
	Total uint64             `json:"total"`
}

type ApplyToJoinOrgReq struct {
	OrgId   uint64 `json:"orgId" validate:"required"`
	UserId  uint64 `json:"userId"`
	Message string `json:"message,optional"`
}

type ApproveRejectRechargeOrderRequest struct {
	OrderNo string `json:"orderNo"`
	Action  string `json:"action"` // "approve" or "reject"
	Reason  string `json:"reason,optional"`
}

type AssignRoleRequest struct {
	UserId uint64 `json:"userId" validate:"required"`
	RoleId uint64 `json:"roleId" validate:"required"`
}

type BaseData struct {
	Id       uint64 `json:"id"`
	DataID   uint64 `json:"dataId"`
	DataType string `json:"dataType"`
	Name     string `json:"name"`
	Comment  string `json:"comment"`
}

type BaseDataFilterResponse struct {
	Response
	Data BaseDataFilterResponseData `json:"data,omitempty"`
}

type BaseDataFilterResponseData struct {
	BillingMethod  []BaseData `json:"billingMethod"`
	Region         []BaseData `json:"region"`
	Supplier       []BaseData `json:"supplier"`
	Processor      []BaseData `json:"processor"`
	GPUModel       []BaseData `json:"gpuModel"`
	GraphicsMemory []BaseData `json:"graphicsMemory"`
	CPUModel       []BaseData `json:"cpuModel"`
	ProcessorCount []BaseData `json:"processorCount"`
	Image          []BaseData `json:"image"`
	IP             []BaseData `json:"ip"`
}

type BaseDataListRequest struct {
	DataType string `json:"data_type"`
	Name     string `json:"name"`
	PaginationRequest
}

type BaseDataListResponse struct {
	Response
	Data BaseDataListResponseData `json:"data,omitempty"`
}

type BaseDataListResponseData struct {
	BaseDataList []BaseData `json:"baseDataList"`
	Total        uint64     `json:"total"`
}

type BaseDataRequest struct {
	DataType string `json:"dataType"`
	Name     string `json:"name"`
	Comment  string `json:"comment"`
}

type BaseResponse struct {
	Response
	Data BaseData `json:"data,omitempty"`
}

type Bucket struct {
	BucketId   uint64 `json:"bucketId"`           // Bucket ID
	BucketName string `json:"bucketName"`         // Bucket name
	UserId     uint64 `json:"userId"`             // User ID
	Region     string `json:"region"`             // Region
	IsDeleted  int64  `json:"isDeleted"`          // Soft delete flag
	DeletedAt  string `json:"deletedAt,optional"` // Deletion time
	CreatedAt  string `json:"createdAt"`          // Creation time
	UpdatedAt  string `json:"updatedAt"`          // Last update time
}

type BucketResponse struct {
	Response
	Data Bucket `json:"data,omitempty"`
}

type CallbackRequest struct {
	Code string `form:"code"`
}

type CallbackResponse struct {
	AccessToken  string    `json:"accessToken"`
	AccessExpire int64     `json:"accessExpire"`
	Message      string    `json:"message"`
	Raw          string    `json:"raw"`
	UserInfo     *UserInfo `json:"userInfo"`
}

type CaptchaResponse struct {
	Response
	Data CaptchaResponseData `json:"data,omitempty"`
}

type CaptchaResponseData struct {
	CaptchaId   string `json:"captchaId"`
	ImageBase64 string `json:"imageBase64"`
}

type CreateBucketRequest struct {
	BucketName string `json:"bucketName"`
	Region     string `json:"region"`
}

type CreateBucketResponse struct {
	Response
	Data CreateBucketResponseData `json:"data,omitempty"`
}

type CreateBucketResponseData struct {
	Bucket Bucket `json:"bucket"`
}

type CreateDiscountRequest struct {
	OrgId      uint64 `json:"orgId"`      // Organization ID
	ResourceId uint64 `json:"resourceId"` // Resource ID
	DiscountBase
}

type CreateImageRequest struct {
	ImageName string `json:"imageName"` // Docker image name
}

type CreateInstanceLogRequest struct {
	InstanceId uint64 `json:"instanceId"`
	UserId     uint64 `json:"userId"`
	Action     string `json:"action"`
}

type CreateInstanceRequest struct {
	UserId        uint64 `json:"userId"`
	ServerId      uint64 `json:"serverId"`
	ImageId       uint64 `json:"ImageId"`
	Ip            uint64 `json:"ip"`
	Port          string `json:"port"`
	ContainerPort string `json:"containerPort"`
	GpuCores      uint64 `json:"gpuCores"`
	Memory        uint64 `json:"memory"`
	DiskPath      string `json:"diskPath"`
	Cost          uint64 `json:"cost"`
	MountPath     string `json:"mountPath"`
}

type CreateInstanceResponse struct {
	Response
	Data CreateInstanceResponseData `json:"data,omitempty"`
}

type CreateInstanceResponseData struct {
	InstanceId    uint64 `json:"instanceId"`
	Name          string `json:"name"`
	State         string `json:"state"`
	UserId        uint64 `json:"userId"`
	ServerId      uint64 `json:"serverId"`
	ImageId       uint64 `json:"imageId"`
	Ip            uint64 `json:"ip"`
	Port          string `json:"port"`
	ContainerPort string `json:"containerPort"`
	GpuCores      uint64 `json:"gpuCores"`
	Memory        uint64 `json:"memory"`
	DiskPath      string `json:"diskPath"`
	Cost          uint64 `json:"cost"`
	MountPath     string `json:"mountPath"`
}

type CreateObjectRequest struct {
	BucketId uint64 `json:"bucketId"` // Bucket ID
	Key      string `json:"key"`      // Object key/name
	Path     string `json:"path"`     // Object path
}

type CreatePermissionRequest struct {
	Name        string `json:"name" validate:"required"`
	Code        string `json:"code" validate:"required"`
	Description string `json:"description"`
}

type CreateRechargeOrderData struct {
	OrgId     uint64 `json:"orgId"`
	PayMethod uint64 `json:"payMethod"`
	Amount    int64  `json:"amount"`
	Title     string `json:"title"`
	OrderNo   string `json:"orderNo"`
	Url       string `json:"url"`
}

type CreateRechargeOrderRequest struct {
	OrgId     uint64 `json:"orgId"`
	PayMethod uint64 `json:"payMethod"`
	PayMoney  int64  `json:"payMoney"`
}

type CreateRechargeOrderResponse struct {
	Response
	Data CreateRechargeOrderData `json:"data,omitempty"`
}

type CreateResourceUserRequest struct {
	UserId       uint64 `json:"userId"`
	ResourceId   uint64 `json:"resourceId"`
	OrgId        uint64 `json:"orgId"`
	ResourceType string `json:"resourceType"`
	Stat         string `json:"stat"`
	StartAt      string `json:"startAt,optional"`
	StopAt       string `json:"stopAt,optional"`
}

type CreateRoleRequest struct {
	Name        string   `json:"name" validate:"required"`
	Description string   `json:"description"`
	Permissions []uint64 `json:"permissions"` // Permission IDs
}

type CreateServerDiscountRequest struct {
	OrgId    uint64 `json:"orgId"`    // Organization ID
	ServerId uint64 `json:"serverId"` // Server ID
	DiscountBase
}

type CreateServerRequest struct {
	ServerId       uint64 `json:"serverId"`
	BillingMethod  uint64 `json:"billingMethod"`
	Region         uint64 `json:"region"`
	Supplier       uint64 `json:"supplier"`
	Processor      uint64 `json:"processor"`
	GpuModel       uint64 `json:"gpuModel"`
	GpuCount       uint64 `json:"gpuCount"`
	GraphicsMemory uint64 `json:"graphicsMemory"`
	CpuModel       uint64 `json:"cpuModel"`
	CpuCores       uint64 `json:"cpuCores"`
	ProcessorCount uint64 `json:"processorCount"`
	Memory         uint64 `json:"memory"`
	SystemDisk     uint64 `json:"systemDisk"`
	DataDisk       uint64 `json:"dataDisk"`
	MaxDataDisk    uint64 `json:"maxDataDisk"`
	SpeedDesc      string `json:"speedDesc"`
	GpuDriver      string `json:"gpuDriver"`
	CudaVersion    string `json:"cudaVersion"`
	Cost           uint64 `json:"cost"`
	Available      uint64 `json:"available"`
	Total          uint64 `json:"total"`
	ExpireDate     string `json:"expireDate"`
}

type CreateTransactionRecordsRequest struct {
	UserId       uint64 `json:"userId"`
	OrgId        uint64 `json:"orgId"`
	TransType    uint64 `json:"transType"`
	PayType      string `json:"payType"`
	CurrencyCode string `json:"currencyCode"`
	Detail       string `json:"detail"`
	OrderNo      string `json:"orderNo"`
	Amount       int64  `json:"amount"`
	Balance      int64  `json:"balance"`
}

type DailyUsageItem struct {
	UsageId         uint64 `json:"usageId"`
	OrgId           uint64 `json:"orgId"`
	UserId          uint64 `json:"userId"`
	UsageDate       string `json:"usageDate"`
	ResourceId      uint64 `json:"resourceId"`
	UsageMinAmount  int64  `json:"usageMinAmount"`
	UsageHourAmount int64  `json:"usageHourAmount"`
	UnitHourPrice   int64  `json:"unitHourPrice"`
	DiscountId      uint64 `json:"discountId"`
	Discount        int64  `json:"discount"`
}

type DailyUsageListRequest struct {
	OrgId     uint64 `json:"orgId,optional"`
	UserId    uint64 `json:"userId,optional"`
	StartDate string `json:"startDate,optional"`
	EndDate   string `json:"endDate,optional"`
	PaginationRequest
}

type DailyUsageListResponse struct {
	Response
	Data DailyUsageListResponseData `json:"data,omitempty"`
}

type DailyUsageListResponseData struct {
	Items []DailyUsageItem `json:"items"`
	Total uint64           `json:"total"`
}

type DeleteBaseDataRequest struct {
	Id uint64 `json:"id"`
}

type DeleteBucketRequest struct {
	BucketId uint64 `json:"bucketId"`
}

type DeleteDiscountRequest struct {
	DiscountId uint64 `json:"discountId"`
}

type DeleteImageRequest struct {
	ImageId uint64 `json:"imageId"`
}

type DeleteObjectRequest struct {
	BucketName string `json:"bucketName"`
	ObjectKey  string `json:"objectKey"`
}

type DeleteObjectResponse struct {
	Response
}

type DeletePermissionRequest struct {
	Id uint64 `path:"id"`
}

type DeleteResourceOrgRequest struct {
	ResourceId uint64 `json:"ResourceId" validate:"required"`
	OrgId      uint64 `json:"orgId" validate:"required"`
}

type DeleteResourceRequest struct {
	Id uint64 `path:"id"`
}

type DeleteRoleRequest struct {
	Id uint64 `path:"id"`
}

type DeleteServerDiscountRequest struct {
	SrvDiscountId uint64 `json:"srvDiscountId"`
}

type DeleteServerOrgRequest struct {
	ServerId uint64 `json:"serverId" validate:"required"`
	OrgId    uint64 `json:"orgId" validate:"required"`
}

type DeleteServerTagRequest struct {
	ServerId uint64 `json:"serverId"`
	TagID    int    `json:"tagId"`
}

type Discount struct {
	DiscountId uint64 `json:"discountId"` // Discount ID
	OrgId      uint64 `json:"orgId"`      // Organization ID
	ResourceId uint64 `json:"resourceId"` // Resource ID
	DiscountBase
	IsDeleted int64  `json:"isDeleted"`          // Soft delete flag
	DeletedAt string `json:"deletedAt,optional"` // Deletion time
	CreatedAt string `json:"createdAt"`          // Creation time
	CreatedBy uint64 `json:"createdBy"`          // Creator ID
}

type DiscountBase struct {
	Memo      string `json:"memo,optional"` // Optional memo
	Startdate string `json:"startdate"`     // Discount start date
	Enddate   string `json:"enddate"`       // Discount end date
	Discount  int64  `json:"discount"`      // Discount value (100 means 10.0)
}

type DiscountResponse struct {
	Response
	Data Discount `json:"data,omitempty"`
}

type DownloadRequest struct {
	File string `path:"file"`
}

type EmailcodeloginRequest struct {
	Email string `json:"email"`
	Code  string `json:"code"`
}

type GLoginRequest struct {
	RedirectURL string `form:"redirectUrl,optional"`
}

type GLoginResponse struct {
	AuthURL string `json:"authUrl"`
}

type GetBucketRequest struct {
	BucketId uint64 `json:"bucketId"`
}

type GetDiscountRequest struct {
	DiscountId uint64 `json:"discountId"`
}

type GetImageRequest struct {
	ImageId uint64 `json:"imageId"`
}

type GetObjectRequest struct {
	ObjId uint64 `json:"objId"`
}

type GetRoleRequest struct {
	Id uint64 `path:"id"`
}

type GetServerDiscountRequest struct {
	SrvDiscountId uint64 `json:"srvDiscountId"`
}

type GetUsersRoleRequest struct {
	UserId uint64 `json:"userId"`
}

type GetpermissionRequest struct {
	Id uint64 `path:"id"`
}

type GpuTypesResp struct {
	Response
	Data []GpusResp `json:"data,omitempty"`
}

type GpusResp struct {
	ID       int    `json:"id"`
	GpuName  string `json:"gpuName"`
	IdleNum  int    `json:"idleNum"`
	TotalNum int    `json:"totalNum"`
}

type HelloRequest struct {
	Name string `path:"name,options=you|me"`
}

type HtmlResponse struct {
	ContentType string `header:"Content-Type"` // Set content type header
	Body        string `body:""`               // HTML content
}

type Image struct {
	ImageId   uint64 `json:"imageId"`
	ImageName string `json:"imageName"` // Docker image name
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type ImageResponse struct {
	Response
	Data Image `json:"data,omitempty"`
}

type Instance struct {
	InstanceId    uint64 `json:"instanceId"`
	Name          string `json:"name"`
	State         string `json:"state"`
	UserId        uint64 `json:"userId"`
	ServerId      uint64 `json:"serverId"`
	ImageId       uint64 `json:"imageId"`
	Ip            uint64 `json:"ip"`
	Port          string `json:"port"`
	ContainerPort string `json:"containerPort"`
	GpuCores      uint64 `json:"gpuCores"`
	Memory        uint64 `json:"memory"`
	DiskPath      string `json:"diskPath"`
	Cost          uint64 `json:"cost"`
	MountPath     string `json:"mountPath"`
}

type InstanceListRequest struct {
	UserId   uint64 `json:"userId,optional"`
	ServerId uint64 `json:"serverId,optional"`
	PaginationRequest
}

type InstanceListResponse struct {
	Response
	Data InstanceListResponseData `json:"data,omitempty"`
}

type InstanceListResponseData struct {
	Instances []Instance `json:"instances"`
	Total     uint64     `json:"total"`
}

type InstanceLog struct {
	Id         uint64 `json:"id"`
	InstanceId uint64 `json:"instanceId"`
	UserId     uint64 `json:"userId"`
	Action     string `json:"action"`
	CreatedAt  string `json:"createdAt"`
	UpdatedAt  string `json:"updatedAt"`
}

type InstanceLogResponse struct {
	Response
	Data InstanceLog `json:"data,omitempty"`
}

type InstancePortMapping struct {
	ServerId      uint64 `json:"serverId"`
	InstanceId    uint64 `json:"instanceId"`
	Port          uint64 `json:"port"`
	ContainerPort uint64 `json:"containerPort"`
}

type LeaveOrgReq struct {
	OrgId  uint64 `json:"orgId" validate:"required"`
	UserId uint64 `json:"userId"`
}

type ListAllRechargeOrdersData struct {
	Orders []RechargeOrderData `json:"orders"`
	Total  uint64              `json:"total"`
}

type ListAllRechargeOrdersRequest struct {
	Status    string `json:"status,optional"`
	PayMethod uint64 `json:"payMethod"`
	PaginationRequest
}

type ListAllRechargeOrdersResponse struct {
	Response
	Data ListAllRechargeOrdersData `json:"data,omitempty"`
}

type ListBucketRequest struct {
	Region string `json:"region,optional"` // Optional filter by region
	PaginationRequest
}

type ListBucketResponse struct {
	Response
	Data ListBucketResponseData `json:"data,omitempty"`
}

type ListBucketResponseData struct {
	Buckets []Bucket `json:"buckets"`
	Total   uint64   `json:"total"`
}

type ListDiscountRequest struct {
	OrgId      uint64 `json:"orgId,optional"`      // Optional filter by org
	ResourceId uint64 `json:"resourceId,optional"` // Optional filter by resource
	PaginationRequest
}

type ListDiscountResponse struct {
	Response
	Data ListDiscountResponseData `json:"data,omitempty"`
}

type ListDiscountResponseData struct {
	Discounts []Discount `json:"discounts"`
	Total     uint64     `json:"total"`
}

type ListImagesRequest struct {
	ImageName string `json:"imageName,optional"` // Optional filter by image name
	PaginationRequest
}

type ListImagesResponse struct {
	Response
	Data ListImagesResponseData `json:"data,omitempty"`
}

type ListImagesResponseData struct {
	Images []Image `json:"images"`
	Total  uint64  `json:"total"`
}

type ListInstanceLogRequest struct {
	InstanceId uint64 `json:"instanceId,optional"`
	UserId     uint64 `json:"userId,optional"`
	Action     string `json:"action,optional"`
	PaginationRequest
}

type ListInstanceLogResponse struct {
	Response
	Data ListInstanceLogResponseData `json:"data,omitempty"`
}

type ListInstanceLogResponseData struct {
	Logs  []InstanceLog `json:"logs"`
	Total uint64        `json:"total"`
}

type ListObjectRequest struct {
	BucketId uint64 `json:"bucketId,optional"` // Optional filter by bucket
	Key      string `json:"key,optional"`      // Optional filter by key
	PaginationRequest
}

type ListObjectResponse struct {
	Response
	Data ListObjectResponseData `json:"data,omitempty"`
}

type ListObjectResponseData struct {
	Objects []Object `json:"objects"`
	Total   uint64   `json:"total"`
}

type ListObjectsResponse struct {
	Response
	Data ListObjectsResponseData `json:"data,omitempty"`
}

type ListObjectsResponseData struct {
	Objects []Object `json:"objects"`
	Total   uint64   `json:"total"`
}

type ListRechargeHistoryData struct {
	Orders []RechargeOrderData `json:"orders"`
	Total  uint64              `json:"total"`
}

type ListRechargeHistoryRequest struct {
	UserId uint64 `json:"userId"`
	PaginationRequest
}

type ListRechargeHistoryResponse struct {
	Response
	Data ListRechargeHistoryData `json:"data,omitempty"`
}

type ListResourceUserRequest struct {
	UserId       uint64 `json:"userId,optional"`
	ResourceId   uint64 `json:"resourceId,optional"`
	OrgId        uint64 `json:"orgId,optional"`
	ResourceType string `json:"resourceType,optional"`
	Stat         string `json:"stat,optional"`
	PaginationRequest
}

type ListResourceUserResponse struct {
	Response
	Data ListResourceUserResponseData `json:"data,omitempty"`
}

type ListResourceUserResponseData struct {
	Resources []ResourceUser `json:"resources"`
	Total     uint64         `json:"total"`
}

type ListServerDiscountRequest struct {
	OrgId    uint64 `json:"orgId,optional"`    // Optional filter by org
	ServerId uint64 `json:"serverId,optional"` // Optional filter by server
	PaginationRequest
}

type ListServerDiscountResponse struct {
	Response
	Data ListServerDiscountResponseData `json:"data,omitempty"`
}

type ListServerDiscountResponseData struct {
	ServerDiscounts []ServerDiscount `json:"serverDiscounts"`
	Total           uint64           `json:"total"`
}

type LoginRequest struct {
	Email     string `json:"email"`
	Password  string `json:"password"`
	Captcha   string `json:"captcha"`
	CaptchaId string `json:"captchaId"`
}

type LoginResponse struct {
	Response
	Data LoginResponseData `json:"data,omitempty"`
}

type LoginResponseData struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	Orgs         []Org  `json:"orgs"`
}

type MinuteUsageItem struct {
	Id            uint64 `json:"id"`
	UsageId       uint64 `json:"usageId"`
	OrgId         uint64 `json:"orgId"`
	UserId        uint64 `json:"userId"`
	ResourceId    uint64 `json:"resourceId"`
	UsageDatetime string `json:"usageDatetime"`
	Fee           int64  `json:"fee"`
	Discount      int64  `json:"discount"`
}

type MinuteUsageListRequest struct {
	UsageId       uint64 `json:"usageId,optional"`
	OrgId         uint64 `json:"orgId,optional"`
	UserId        uint64 `json:"userId,optional"`
	StartDatetime string `json:"startDatetime,optional"`
	EndDatetime   string `json:"endDatetime,optional"`
	PaginationRequest
}

type MinuteUsageListResponse struct {
	Response
	Data MinuteUsageListResponseData `json:"data,omitempty"`
}

type MinuteUsageListResponseData struct {
	Items []MinuteUsageItem `json:"items"`
	Total uint64            `json:"total"`
}

type Object struct {
	ObjId     uint64 `json:"objId"`     // Object ID
	BucketId  uint64 `json:"bucketId"`  // Bucket ID
	UserId    uint64 `json:"userId"`    // User ID
	Key       string `json:"key"`       // Object key/name
	Path      string `json:"path"`      // Object path
	CreatedAt string `json:"createdAt"` // Creation time
	UpdatedAt string `json:"updatedAt"` // Last update time
}

type ObjectResponse struct {
	Response
	Data Object `json:"data,omitempty"`
}

type OrderRecords struct {
	Id            uint64 `json:"id"`
	OrderNo       string `json:"orderNo"`
	InstanceId    uint64 `json:"instanceId"`
	RunningTime   uint64 `json:"runningTime"`
	CreatedAt     uint64 `json:"createdAt"`
	BillingMethod uint64 `json:"billingMethod"`
	OrderAmount   uint64 `json:"orderAmount"`
	Discount      uint64 `json:"discount"`
	ActualAmount  uint64 `json:"actualAmount"`
	UserId        uint64 `json:"userId"`
	OrderType     uint64 `json:"orderType"`
}

type OrderRecordsListRequest struct {
	UserId         uint64 `json:"userId"`
	OrderType      uint   `json:"orderType"`
	BeginCreatedAt uint64 `json:"beginCreatedAt"`
	EndCreatedAt   uint64 `json:"endCreatedAt"`
	OrderNo        string `json:"orderNo"`
	PaginationRequest
}

type OrderRecordsListResponse struct {
	Response
	Data OrderRecordsListResponseData `json:"data,omitempty"`
}

type OrderRecordsListResponseData struct {
	Items []OrderRecords `json:"items"`
	Total int            `json:"total"`
}

type Org struct {
	OrgId   uint64 `json:"orgId"`
	OrgName string `json:"orgName"`
	Role    string `json:"role"`
}

type OrgInviteUserReq struct {
	OrgId  uint64 `json:"orgId" validate:"required"`
	UserId uint64 `json:"userId"`
	Email  string `json:"email" validate:"required,email"`
	Role   string `json:"role" validate:"required,oneof=member admin"`
}

type PaginationRequest struct {
	Page     uint64 `json:"page"`
	PageSize uint64 `json:"pageSize"`
}

type Permission struct {
	Id          uint64 `json:"id"`
	Name        string `json:"name"`
	Code        string `json:"code"`
	Description string `json:"description"`
	CreatedAt   int64  `json:"createdAt"`
	UpdatedAt   int64  `json:"updatedAt"`
}

type PermissionListRequest struct {
	Name string `json:"name,optional"`
	Code string `json:"code,optional"`
	PaginationRequest
}

type PermissionListResponse struct {
	Response
	Data PermissionListResponseData `json:"data,omitempty"`
}

type PermissionListResponseData struct {
	Permissions []Permission `json:"permissions"`
	Total       uint64       `json:"total"`
}

type PermissionResponse struct {
	Response
	Data Permission `json:"data,omitempty"`
}

type PhonecodeloginRequest struct {
	Phonenum string `json:"phonenum"`
	Code     string `json:"code"`
}

type RechargeOrderData struct {
	OrderNo   string `json:"orderNo"`
	UserId    uint64 `json:"userId"`
	Amount    int64  `json:"amount"`
	PayMethod uint64 `json:"payMethod"`
	Status    string `json:"status"`
	CreatedAt uint64 `json:"createdAt"`
}

type RechargeOrderResponse struct {
	Response
	Data RechargeOrderData `json:"data,omitempty"`
}

type RegisterRequest struct {
	Username  string `json:"username"`
	Nickname  string `json:"nickname"`
	Email     string `json:"email"`
	Phone     string `json:"phone"`
	Password  string `json:"password"`
	Captcha   string `json:"captcha"`
	CaptchaId string `json:"captchaId"`
}

type RegisterResponse struct {
	Response
	Data RegisterResponseData `json:"data,omitempty"`
}

type RegisterResponseData struct {
	UserId   uint64 `json:"userId"`
	Username string `json:"username"`
	Nickname string `json:"nickname"`
	Email    string `json:"email"`
	Phone    string `json:"phone"`
	Orgs     []Org  `json:"orgs"`
}

type ResetPasswordRequest struct {
	Email       string `json:"email"`
	OldPassword string `json:"oldPassword"`
	NewPassword string `json:"newPassword"`
}

type ResourceCreateRequest struct {
	ResourceType  string `json:"resourceType"`
	UnitMinPrice  int64  `json:"unitMinPrice"`
	UnitHourPrice int64  `json:"unitHourPrice"`
	UnitDayPrice  int64  `json:"unitDayPrice"`
}

type ResourceItem struct {
	ResourceId    uint64 `json:"resourceId"`
	ResourceType  string `json:"resourceType"`
	UnitMinPrice  int64  `json:"unitMinPrice"`
	UnitHourPrice int64  `json:"unitHourPrice"`
	UnitDayPrice  int64  `json:"unitDayPrice"`
	IsDeleted     int64  `json:"isDeleted"`
	CreatedAt     string `json:"createdAt"`
	CreatedBy     uint64 `json:"createdBy"`
}

type ResourceListRequest struct {
	OrgId        uint64 `json:"orgId,optional"`
	ResourceType string `json:"resourceType,optional"`
	PaginationRequest
}

type ResourceListResponse struct {
	Response
	Data ResourceListResponseData `json:"data,omitempty"`
}

type ResourceListResponseData struct {
	Items []ResourceItem `json:"items"`
	Total uint64         `json:"total"`
}

type ResourceOrg struct {
	Id          uint64 `json:"id"`
	ResourceId  uint64 `json:"ResourceId"`
	OrgId       uint64 `json:"orgId"`
	CreatedAt   int64  `json:"createdAt"`
	UpdatedAt   int64  `json:"updatedAt"`
	Description string `json:"description,optional"`
}

type ResourceOrgResponse struct {
	Response
	Data ResourceOrg `json:"data,omitempty"`
}

type ResourceResponse struct {
	Response
	Data ResourceItem `json:"data,omitempty"`
}

type ResourceUpdateRequest struct {
	ResourceId    uint64 `json:"resourceId"`
	OrgId         uint64 `json:"orgId,optional"`
	ResourceType  string `json:"resourceType,optional"`
	UnitMinPrice  int64  `json:"unitMinPrice,optional"`
	UnitHourPrice int64  `json:"unitHourPrice,optional"`
	UnitDayPrice  int64  `json:"unitDayPrice,optional"`
}

type ResourceUser struct {
	Id           uint64 `json:"id"`
	UserId       uint64 `json:"userId"`
	ResourceId   uint64 `json:"resourceId"`
	OrgId        uint64 `json:"orgId"`
	ResourceType string `json:"resourceType"`
	Stat         string `json:"stat"`
	StartAt      string `json:"startAt,optional"`
	StopAt       string `json:"stopAt,optional"`
	CreatedAt    string `json:"createdAt"`
}

type ResourceUserResponse struct {
	Response
	Data ResourceUser `json:"data,omitempty"`
}

type Response struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
	Info    string `json:"info,omitempty"`
}

type RestPassRequest struct {
	NewPassword string `json:"newPassword"`
}

type RevokeRoleRequest struct {
	UserId uint64 `json:"userId"`
	RoleId uint64 `json:"roleId"`
}

type Role struct {
	Id          uint64 `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	CreatedAt   int64  `json:"createdAt"`
	UpdatedAt   int64  `json:"updatedAt"`
}

type RoleListRequest struct {
	Name string `json:"name,optional"`
	PaginationRequest
}

type RoleListResponse struct {
	Response
	Data RoleListResponseData `json:"data,omitempty"`
}

type RoleListResponseData struct {
	Roles []Role `json:"roles"`
	Total uint64 `json:"total"`
}

type RoleResponse struct {
	Response
	Data Role `json:"data,omitempty"`
}

type SendemailcodeRequest struct {
	Email     string `json:"email"`
	Captcha   string `json:"captcha"`
	CaptchaId string `json:"captchaId"`
}

type SendphonecodeRequest struct {
	Phonenum  string `json:"phonenum"`
	Captcha   string `json:"captcha"`
	CaptchaId string `json:"captchaId"`
}

type Server struct {
	ServerId       uint64 `json:"serverId"`
	BillingMethod  uint64 `json:"billingMethod"`
	Region         uint64 `json:"region"`
	Supplier       uint64 `json:"supplier"`
	Processor      uint64 `json:"processor"`
	GpuModel       uint64 `json:"gpuModel"`
	GpuCount       uint64 `json:"gpuCount"`
	GraphicsMemory uint64 `json:"graphicsMemory"`
	CpuModel       uint64 `json:"cpuModel"`
	CpuCores       uint64 `json:"cpuCores"`
	ProcessorCount uint64 `json:"processorCount"`
	Memory         uint64 `json:"memory"`
	SystemDisk     uint64 `json:"systemDisk"`
	DataDisk       uint64 `json:"dataDisk"`
	MaxDataDisk    uint64 `json:"maxDataDisk"`
	SpeedDesc      string `json:"speedDesc"`
	GpuDriver      string `json:"gpuDriver"`
	CudaVersion    string `json:"cudaVersion"`
	Cost           uint64 `json:"cost"`
	Available      uint64 `json:"available"`
	Total          uint64 `json:"total"`
	ExpireDate     string `json:"expireDate"`
}

type ServerDiscount struct {
	SrvDiscountId uint64 `json:"srvDiscountId"` // Server discount ID
	OrgId         uint64 `json:"orgId"`         // Organization ID
	ServerId      uint64 `json:"serverId"`      // Server ID
	DiscountBase
	IsDeleted int64  `json:"isDeleted"`          // Soft delete flag
	DeletedAt string `json:"deletedAt,optional"` // Deletion time
	CreatedAt string `json:"createdAt"`          // Creation time
	CreatedBy uint64 `json:"createdBy"`          // Creator ID
}

type ServerDiscountResponse struct {
	Response
	Data ServerDiscount `json:"data,omitempty"`
}

type ServerIpMapping struct {
	ServerId uint64 `db:"serverId"`
	Ip       string `db:"ip"`
}

type ServerListDataResp struct {
	Servers   []Server `json:"servers"`
	PageIndex int      `json:"pageIndex"`
	PageSize  int      `json:"pageSize"`
	Offset    int      `json:"offset"`
	MaxPage   int      `json:"maxPage"`
	Total     int      `json:"total"`
	Page      int      `json:"page"`
}

type ServerListRequest struct {
	RegionId     int `json:"regionId"`
	TagId        int `json:"tagId"`
	IsPayMin     int `json:"isPayMin"`
	IsPayDaily   int `json:"isPayDaily"`
	IsPayMonthly int `json:"isPayMonthly"`
	IsPayYearly  int `json:"isPayYearly"`
	GpuModel     int `json:"gpuModel"`
	GpuCount     int `json:"gpuCount"`
	PaginationRequest
}

type ServerListResp struct {
	Response
	Data ServerListDataResp `json:"data,omitempty"`
}

type ServerListResponse struct {
	Response
	Data ServerListDataResp `json:"data,omitempty"`
}

type ServerOrg struct {
	Id          uint64 `json:"id"`
	ServerId    uint64 `json:"serverId"`
	OrgId       uint64 `json:"orgId"`
	CreatedAt   int64  `json:"createdAt"`
	UpdatedAt   int64  `json:"updatedAt"`
	Description string `json:"description,optional"`
}

type ServerOrgResponse struct {
	Response
	Data ServerOrg `json:"data,omitempty"`
}

type ServerUpdateResponse struct {
	Response
	Data Server `json:"data,omitempty"`
}

type Servers struct {
	ServerId         uint64 `json:"serverId"`
	ServerName       string `json:"serverName"`
	IsOnline         int64  `json:"isOnline"`
	BillingMethod    uint64 `json:"billingMethod"` // 计费方式
	RegionId         uint64 `json:"regionId"`      // 地区
	IsPayMin         int64  `json:"isPayMin"`
	IsPayDaily       int64  `json:"isPayDaily"`
	IsPayMonthly     int64  `json:"isPayMonthly"`
	IsPayYearly      int64  `json:"isPayYearly"`
	PayPrices        string `json:"payPrices"`
	DiskPayPrices    string `json:"diskPayPrices"`
	Supplier         uint64 `json:"supplier"`         // 供应商
	Processor        uint64 `json:"processor"`        // 处理器类型
	GpuModel         uint64 `json:"gpuModel"`         // GPU型号
	GpuCount         uint64 `json:"gpuCount"`         // GPU数量
	GpuUsed          int64  `json:"gpuUsed"`          // 已使用GPU数量
	GpuMem           uint64 `json:"gpuMem"`           // 显存
	CpuModel         uint64 `json:"cpuModel"`         // CPU型号
	CpuCores         uint64 `json:"cpuCores"`         // CPU核数
	CpuFrequency     int64  `json:"cpuFrequency"`     // cpu频率
	ThreadCount      uint64 `json:"threadCount"`      // 处理器线程数量
	Memory           uint64 `json:"memory"`           // 内存(GB)
	SystemDisk       uint64 `json:"systemDisk"`       // 系统盘(GB)
	DataDisk         uint64 `json:"dataDisk"`         // 数据盘(GB)
	MaxDataDisk      uint64 `json:"maxDataDisk"`      // 最大数据盘(GB)
	SpeedDesc        string `json:"speedDesc"`        // 运算速度
	OsName           string `json:"osName"`           // 操作系统名称
	OsVersion        string `json:"osVersion"`        // 操作系统版本号
	KernelVersion    string `json:"kernelVersion"`    // 内核版本
	GpuDriver        string `json:"gpuDriver"`        // GPU驱动
	CudaVersion      string `json:"cudaVersion"`      // cuda版本
	DockerVersion    string `json:"dockerVersion"`    // Docker版本号
	NvidiaDocker     int64  `json:"nvidiaDocker"`     // 是否支持nvidia-docker
	NetworkDownSpeed int64  `json:"networkDownSpeed"` // 网络下载速度
	NetworkUpSpeed   int64  `json:"networkUpSpeed"`   // 网络上传速度
	AgentVersion     string `json:"agentVersion"`     // 代理版本号
	Cost             uint64 `json:"cost"`             // 费用
	Available        uint64 `json:"available"`        // 空闲数量
	Total            uint64 `json:"total"`            // 可用总量
	ExpireDate       uint64 `json:"expireDate"`       // 到期时间
	RegionName       string `json:"regionName"`       // 地区
	Tags             []Tag  `json:"tags"`
}

type StartInstancesRequest struct {
	InstanceId uint64 `json:"instanceId"`
}

type StartResourceUserRequest struct {
	UserId     uint64 `json:"userId"`
	ResourceId uint64 `json:"resourceId"`
}

type StopInstanceLogRequest struct {
	InstanceId uint64 `json:"instanceId"`
	UserId     uint64 `json:"userId"`
}

type StopInstancesRequest struct {
	InstanceId uint64 `json:"instanceId"`
}

type StopResourceUserRequest struct {
	UserId     uint64 `json:"userId"`
	ResourceId uint64 `json:"resourceId"`
}

type Tag struct {
	TagID   int    `json:"tagId"`
	TagName string `json:"tagName"`
}

type TagsResp struct {
	Response
	Data []Tag `json:"data,omitempty"`
}

type TerminateInstancesRequest struct {
	InstanceId uint64 `json:"instanceId"`
}

type TransactionRecords struct {
	Id           int64  `json:"id"`
	UserId       uint64 `json:"userId"`
	OrgId        uint64 `json:"orgId"`
	CreatedAt    uint64 `json:"createdAt"`
	TransType    uint64 `json:"transType"`
	PayType      string `json:"payType"`
	CurrencyCode string `json:"currencyCode"`
	Detail       string `json:"detail"`
	OrderNo      string `json:"orderNo"`
	Username     string `json:"username"`
	Amount       int64  `json:"amount"`
	Balance      int64  `json:"balance"`
}

type TransactionRecordsListRequest struct {
	UserId         uint64 `json:"userId"`
	OrgId          uint64 `json:"orgId"`
	TransType      uint64 `json:"TransType"`
	CurrencyCode   string `json:"currencyCode"`
	BeginCreatedAt uint64 `json:"beginCreatedAt"`
	EndCreatedAt   uint64 `json:"endCreatedAt"`
	OrderNo        string `json:"orderNo"`
	PaginationRequest
}

type TransactionRecordsListResponse struct {
	Response
	Data TransactionRecordsListResponseData `json:"data,omitempty"`
}

type TransactionRecordsListResponseData struct {
	Items []TransactionRecords `json:"items"`
	Total int                  `json:"total"`
}

type UpdateBucketRequest struct {
	BucketId   uint64 `json:"bucketId"`   // Bucket ID
	BucketName string `json:"bucketName"` // Bucket name
	Region     string `json:"region"`     // Region
}

type UpdateDiscountRequest struct {
	DiscountId uint64 `json:"discountId"` // Discount ID
	DiscountBase
}

type UpdateImageRequest struct {
	ImageId   uint64 `json:"imageId"`
	ImageName string `json:"imageName"` // Docker image name
}

type UpdateInstanceRequest struct {
	InstanceId    uint64 `json:"instanceId"`             // Identifier for the instance to be updated
	UserId        uint64 `json:"userId,optional"`        // Optional: User ID associated with the instance
	ServerId      uint64 `json:"serverId,optional"`      // Optional: Server ID associated with the instance
	Image         uint64 `json:"image,optional"`         // Optional: Image ID
	Ip            uint64 `json:"ip,optional"`            // Optional: IP address
	Port          string `json:"port,optional"`          // Optional: Port number
	ContainerPort string `json:"containerPort,optional"` // Optional: Container port number
	GpuCores      uint64 `json:"gpuCores,optional"`      // Optional: Number of GPU cores
	Memory        uint64 `json:"memory,optional"`        // Optional: Amount of memory
	DiskPath      string `json:"diskPath,optional"`      // Optional: Disk path
	Cost          uint64 `json:"cost,optional"`          // Optional: Cost
	MountPath     string `json:"mountPath,optional"`     // Optional: Mount path
}

type UpdateObjectRequest struct {
	ObjId uint64 `json:"objId"` // Object ID
	Key   string `json:"key"`   // Object key/name
	Path  string `json:"path"`  // Object path
}

type UpdatePermissionRequest struct {
	Id          uint64 `json:"id" validate:"required"`
	Name        string `json:"name,optional"`
	Code        string `json:"code,optional"`
	Description string `json:"description,optional"`
}

type UpdateResourceUserRequest struct {
	Id           uint64 `json:"id"`
	UserId       uint64 `json:"userId,optional"`
	ResourceId   uint64 `json:"resourceId,optional"`
	OrgId        uint64 `json:"orgId,optional"`
	ResourceType string `json:"resourceType,optional"`
	Stat         string `json:"stat,optional"`
	StartAt      string `json:"startAt,optional"`
	StopAt       string `json:"stopAt,optional"`
}

type UpdateRoleRequest struct {
	Id          uint64   `json:"id" validate:"required"`
	Name        string   `json:"name,optional"`
	Description string   `json:"description,optional"`
	Permissions []uint64 `json:"permissions,optional"` // Permission IDs
}

type UpdateServerDiscountRequest struct {
	SrvDiscountId uint64 `json:"srvDiscountId"` // Server discount ID
	DiscountBase
}

type UpdateUserInfoRequest struct {
	Username string `json:"username,optional"`
	Email    string `json:"email,optional"`
	Phone    string `json:"phone,optional"`
	Nickname string `json:"nickname,optional"`
}

type UploadObjectRequest struct {
	BucketName string `json:"bucketName"`
	ObjectKey  string `json:"objectKey"`
	Content    string `json:"content"`
}

type UploadResponse struct {
	Code int `json:"code"`
}

type UserBalanceData struct {
	UserId       uint64 `json:"userId"`
	Balance      int64  `json:"balance"`
	CurrencyCode string `json:"currencyCode"`
}

type UserBalanceResponse struct {
	Response
	Data []UserBalanceData `json:"data,omitempty"`
}

type UserInfo struct {
	Id            string `json:"id"`
	Name          string `json:"name"`
	Email         string `json:"email"`
	VerifiedEmail bool   `json:"verified_email"`
	Picture       string `json:"picture"`
}

type UserResponse struct {
	Response
	Data UserResponseData `json:"data,omitempty"`
}

type UserResponseData struct {
	UserId    uint64 `json:"userId"`
	Username  string `json:"username"`
	Nickname  string `json:"nickname"`
	Phone     string `json:"phone"`
	Email     string `json:"email"`
	Balance   int64  `json:"balance"`
	IsDeleted int64  `json:"isDeleted"`
	Orgs      []Org  `json:"orgs"`
}

type UserRolesResponse struct {
	Response
	Data UserRolesResponseData `json:"data,omitempty"`
}

type UserRolesResponseData struct {
	Roles []Role `json:"roles"`
}

type XCallbackRequest struct {
	Code string `form:"code"`
}

type XCallbackResponse struct {
	AccessToken  string     `json:"accessToken"`
	AccessExpire int64      `json:"accessExpire"`
	Message      string     `json:"message"`
	Raw          string     `json:"raw"`
	UserInfo     *XUserInfo `json:"userInfo"`
}

type XLoginRequest struct {
	RedirectURL string `form:"redirectUrl,optional"`
}

type XLoginResponse struct {
	AuthURL string `json:"authUrl"`
}

type XUserInfo struct {
	Id            string `json:"id"`
	Name          string `json:"name"`
	Username      string `json:"usernamel"`
	VerifiedEmail bool   `json:"verified_email"`
	Picture       string `json:"picture"`
}
